#!/usr/bin/env python3
import os
import re
import sys
import subprocess
import argparse
from datetime import datetime

def find_main_cpp():
    common = ["main/main.cpp", "main/main.c", "src/main.cpp", "src/main.c", "main.cpp", "main.c"]
    for path in common:
        if os.path.isfile(path):
            with open(path, 'r', encoding='utf-8') as f:
                if 'app_main' in f.read():
                    return path
    for root, _, files in os.walk("."):
        if root.startswith((".\\components", "components")):
            continue
        for file in files:
            if file.endswith(('.cpp', '.c')):
                full = os.path.join(root, file)
                try:
                    with open(full, 'r', encoding='utf-8') as f:
                        if 'app_main' in f.read():
                            return full
                except:
                    continue
    return None

def get_current_git_version():
    try:
        out = subprocess.check_output(
            ['git', 'describe', '--tags', '--long', '--dirty', '--always'],
            stderr=subprocess.DEVNULL
        ).decode().strip()
        return out
    except:
        return "v0.0.0-0-g0000000-dirty"

def get_git_tag():
    try:
        out = subprocess.check_output(['git', 'describe', '--tags', '--abbrev=0'], stderr=subprocess.DEVNULL).decode().strip()
        return out
    except:
        return "untagged"

def get_git_hash():
    try:
        out = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], stderr=subprocess.DEVNULL).decode().strip()
        return f"g{out}"
    except:
        return "g0000000"

def get_full_hash():
    try:
        out = subprocess.check_output(['git', 'rev-parse', 'HEAD'], stderr=subprocess.DEVNULL).decode().strip()
        return out
    except:
        return "0" * 40

def get_build_id():
    return datetime.now().strftime("P%Y%m%d-%H%M%S-%f")[:23]

def read_existing_version_h():
    path = os.path.join("build", "main", "version.h")
    if not os.path.isfile(path):
        return None
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            m = re.match(r'^#define\s+FW_GIT_VERSION\s+"(.*)"', line)
            if m:
                return m.group(1)
    return None

def write_version_h(values):
    os.makedirs(os.path.join("build", "main"), exist_ok=True)
    path = os.path.join("build", "main", "version.h")
    content = f"""// Auto-generated by update_version_comment.py
#ifndef FW_VERSION_H
#define FW_VERSION_H

#define FW_GIT_VERSION "{values['GIT_VERSION']}"
#define FW_GIT_TAG "{values['GIT_TAG']}"
#define FW_GIT_HASH "{values['GIT_HASH']}"
#define FW_FULL_HASH "{values['FULL_HASH']}"
#define FW_BUILD_ID "{values['BUILD_ID']}"

#endif // FW_VERSION_H
"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Wrote {path}")

def read_version_h():
    path = os.path.join("build", "main", "version.h")
    if not os.path.isfile(path):
        print(f"ERROR: {path} not found.")
        sys.exit(1)
    macros = {}
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            m = re.match(r'^#define\s+FW_(\w+)\s+"(.*)"', line)
            if m:
                macros[m.group(1)] = m.group(2)
    return {
        "GIT_VERSION": macros.get("GIT_VERSION", "v0.0.0-0"),
        "GIT_TAG":     macros.get("GIT_TAG", "untagged"),
        "GIT_HASH":    macros.get("GIT_HASH", "g0000000"),
        "FULL_HASH":   macros.get("FULL_HASH", "0"*40),
        "BUILD_ID":    macros.get("BUILD_ID", "P00000000-000000-0000000")
    }

def get_required_components():
    cmake_file = "main/CMakeLists.txt"
    if not os.path.isfile(cmake_file):
        return []
    with open(cmake_file, 'r', encoding='utf-8') as f:
        content = f.read()
    matches = re.findall(r'REQUIRES\s+([^\n]+)', content)
    if not matches:
        return []
    req_line = matches[0]
    req_line = re.sub(r'\\\s*\n', ' ', req_line)
    components = req_line.split()
    return [c.strip() for c in components if c.strip()]

def get_submodule_version(submodule_path):
    try:
        out = subprocess.check_output(
            ['git', '-C', submodule_path, 'describe', '--tags', '--long', '--dirty', '--always'],
            stderr=subprocess.DEVNULL
        ).decode().strip()
        return out
    except:
        return "unknown"

def get_submodule_versions(required_components):
    if not os.path.isfile('.gitmodules'):
        return {}
    submodule_paths = {}
    with open('.gitmodules', 'r', encoding='utf-8') as f:
        for line in f:
            m = re.match(r'\s*path\s*=\s*(.+)', line)
            if m:
                path = m.group(1).strip()
                name = os.path.basename(path)
                submodule_paths[name] = path
    versions = {}
    for comp in required_components:
        if comp in submodule_paths:
            p = submodule_paths[comp]
            if os.path.isdir(p):
                versions[comp] = get_submodule_version(p)
    return versions

def get_git_author():
    try:
        name = subprocess.check_output(['git', 'config', 'user.name'], stderr=subprocess.DEVNULL).decode().strip()
        email = subprocess.check_output(['git', 'config', 'user.email'], stderr=subprocess.DEVNULL).decode().strip()
        if name and email:
            return f"{name} ({email})"
        elif name:
            return name
    except:
        pass
    name = os.environ.get('GIT_AUTHOR_NAME', 'Unknown')
    email = os.environ.get('GIT_AUTHOR_EMAIL', '')
    if email:
        return f"{name} ({email})"
    return name

def extract_file_and_brief(content):
    file_line = ""
    brief_line = ""
    comment_match = re.search(r'/\*\*.*?\*/', content, re.DOTALL)
    if comment_match:
        comment = comment_match.group(0)
        lines = comment.splitlines()
        for line in lines:
            if '@file' in line:
                file_line = line.strip()
            elif '@brief' in line:
                brief_line = line.strip()
                break
    return file_line, brief_line

def rebuild_comment_block(values, submodule_versions, existing_file, existing_brief):
    today = datetime.now().strftime("%Y-%m-%d")
    version_str = values["GIT_VERSION"]
    author = get_git_author()
    if not existing_file:
        existing_file = " * @file "
    if not existing_brief:
        existing_brief = " * @brief "
    lines = []
    lines.append("/**")
    lines.append(existing_file)
    lines.append(existing_brief)
    lines.append(" *")
    lines.append(f" * @author {author}")
    lines.append(f" * @version GIT_VERSION: {version_str}")
    lines.append(f" * @date {today}")
    lines.append(" * @submodules-start")
    if submodule_versions:
        max_len = max(len(name) for name in submodule_versions.keys())
        for name, ver in sorted(submodule_versions.items()):
            lines.append(f" *   {name:<{max_len}} : {ver}")
    else:
        lines.append(" *   (none)")
    lines.append(" * @submodules-end")
    lines.append(" */")
    return '\n'.join(lines)

def write_version_cmake(version, build_dir="build"):
    """Write the CMake variable file that sets PROJECT_VER."""
    os.makedirs(build_dir, exist_ok=True)
    cmake_path = os.path.join(build_dir, "version.cmake")
    with open(cmake_path, "w") as f:
        f.write(f'# Auto-generated by update_version_comment.py\n')
        f.write(f'set(PROJECT_VER "{version}")\n')
    print(f"Wrote {cmake_path} with version {version}")

def update_main_file(filepath, values, submodule_versions):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Update Doxygen comment block only (no struct injection)
    file_line, brief_line = extract_file_and_brief(content)
    new_comment = rebuild_comment_block(values, submodule_versions, file_line, brief_line)
    content = re.sub(r'/\*\*.*?\*/', new_comment, content, flags=re.DOTALL, count=1)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print("INFO: Updated", filepath)

def main():
    parser = argparse.ArgumentParser(description="Update version info in firmware source files.")
    parser.add_argument("--version", help="Exact version string to use (if omitted, derived from Git)")
    args = parser.parse_args()

    if args.version:
        current_version = args.version
        print(f"Using provided version: {current_version}")
    else:
        current_version = get_current_git_version()
        print(f"Current Git version: {current_version}")

    existing_version = read_existing_version_h()
    if existing_version == current_version:
        print("version.h already up-to-date.")
    else:
        print(f"Version changed (was {existing_version}), regenerating version.h...")
        values = {
            "GIT_VERSION": current_version,
            "GIT_TAG": get_git_tag(),
            "GIT_HASH": get_git_hash(),
            "FULL_HASH": get_full_hash(),
            "BUILD_ID": get_build_id()
        }
        write_version_h(values)

    values = read_version_h()
    print("Read values from version.h:", values)

    # Optionally still write version.cmake (if you want to keep that method)
    # But now the main version comes from CMake's own execute_process.
    # You can keep this line for backwards compatibility.
    # write_version_cmake(current_version)

    main_file = find_main_cpp()
    if not main_file:
        print("ERROR: Could not find source file containing 'app_main'.")
        sys.exit(1)
    print("Found main source file:", main_file)

    req_components = get_required_components()
    print("Required components:", req_components)
    submodule_versions = get_submodule_versions(req_components)
    if submodule_versions:
        print("Submodule versions:", submodule_versions)

    update_main_file(main_file, values, submodule_versions)
    print("Done.")

if __name__ == "__main__":
    main()